(defun inspiration-653726 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/653726/"
  (interactive)
  (color-theme-install
   '(inspiration-653726
     ((background-color . "#020000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#BDA197"))))
     (font-lock-constant-face ((t (:foreground "#8520A2"))))
     (font-lock-builtin-face ((t (:foreground "#35AC80"))))
     (font-lock-function-name-face ((t (:foreground "#5A6BB5"))))
     (font-lock-variable-name-face ((t (:foreground "#A52E2D"))))
     (font-lock-keyword-face ((t (:foreground "#268570"))))
     (font-lock-string-face ((t (:foreground "#5A3193"))))
     (font-lock-doc-string-face ((t (:foreground "#5A3193"))))
     (font-lock-type-face ((t (:foreground "#6C8E32"))))
     )))

(provide 'inspiration-653726)